### ISSUE TITLE
Wake On Lan is not showing on Host

### ISSUE THREAD

**Issue by MPeixoto01** [johannesschaefer/simple-network-monitor#1]
Hi there, 
I'm using your container and I'm trying to set some machines waking up throw Lan. When I edit the command wakeonlan it does not appear with the changes made when I go to Edit Host to perform it or even if I make a new command it will not be listed there. But if I run it on command prompt it will work.
Can you give me some info on that?

**Comment by johannesschaefer** [comment]
Hi,

thanks for using my image.
Unfortunately I can't follow your explanations. But let me quickly describe how to setup wake on lan for the hosts correctly.

By default the ether-wake command is included in the docker image. So it should be possible to connect to the running docker container and run `ether-wake 00:00:00:00:00:00`. Please be aware, that the raspberry version is using `etherwake` (without the dash in the command name), so if you running on a raspberry you have to change the wakeonlan command in the setting (setting icon in the top right -> `Edit commands` -> `Edit` wakeonlan and change the `Exec` to `etherwake`).

To create a new host you simply have to click on the `+` icon and create a new host (enter at least a hostname). In the tab `Properties` please enter the key-value-pair with `mac_address` and the MAC address of our host.
In the tab `Commands` just add the new command `wakeonlan` (you can scroll the list of commands).
Save the host and click on the play icon in the Commands column.

That's it. I hope that I didn't miss anything.

You can make the process also a little bit simpler, by using the auto discover feature. Just click the magnifier glass with the plus, select the IP range and start the scan. All host from your network will be shown up in a list and you can select which one you like to add to the list.

Just some final notes, some feature like magic packets and arp discovery may only work, when you bind the docker network interface in host mode. This is also only working on a Linux docker host. So please ensure that you start your container with `--network host`.

Regards
Johannes

**Comment by MPeixoto01** [comment]
Hi again, 
Thanks for that information it was very helpful. 

I have another problem, when I add a new command it doesn't appear in the list of commands in the host commands. And also I tried to do the auto discover with the docker network interface in host mode in a Linux host and it didn't work.

Would appreciate some ideas about what to do or if it exits a command to refresh the command list.

**Comment by johannesschaefer** [comment]
Hi,

thanks for the report. I can reproduce the issue. I will fix this ASAP.

You can try as work around to restart the server. Please ensure that the persited the data out side of your docker container.
It is also possible to export the commands list (in the command overview the export button; this includes the new command) and use this as an inital list for setup the DB. In docker you have to set the environment variables `COMMANDS_FILE` to do this. Please check also [simple-network-monitor-backend/src/main/docker-compose/docker-compose.yml](https://github.com/johannesschaefer/simple-network-monitor/blob/master/simple-network-monitor-backend/src/main/docker-compose/docker-compose.yml) how to set the initial setup file.

**Comment by MPeixoto01** [comment]
Hi,

Thanks a lot for the quick and useful answer.

I understood what you explained that it is possible to add new commands but I think it's limited to 20 because I had to remove some and after that, I was able to run my personalized command.

**Comment by johannesschaefer** [comment]
Please try out the new latest version of the docker image. I did a small fix.
I will release this weekend a new version.

**Comment by johannesschaefer** [comment]
Fixed with the new release.
